version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 # Specify your desired Node.js version
    commands:
      - npm install # Install project dependencies
  build:
    commands:
      - npm run build # Replace with your build script or commands
  post_build:
    commands:
      - aws s3 cp --recursive ./build s3://todomatic/

artifacts:
  files:
    - "build/*"
    - "build/**/*"