version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12 # Specify your desired Node.js version
    commands:
      - npm install # Install project dependencies
  pre_build:
    commands:
      - rm -rf build # Remove the previous build artifacts
  build:
    commands:
      - npm run build # Replace with your build script or commands
  post_build:
    commands:
      - aws s3 cp build/index.html s3://todomatic/todomatic/index.html

artifacts:
  files: '**/*'
  discard-paths: yes
