version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12 # Specify your desired Node.js version
    commands:
      - npm install # Install project dependencies
 pre_build:
  commands:
    - rm -rf build # Remove the previous build artifacts   
  build:
    commands:
      - npm run build # Replace with your build script or commands

artifacts:
  files:
    - '**/*' # Include all project files in the build artifacts
  discard-paths: yes
